name: Create Welcome Issue
on:
  create: # Triggers when the repository branch is first created
  workflow_dispatch: # Allows manual triggering for testing

permissions:
  contents: write
  issues: write

jobs:
  create_welcome_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create welcome issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const title = "🚀 Welcome to DESN368 - Start Here!";
            const labelName = "welcome";

            // Ensure label exists (avoid failures if it's missing)
            try {
              await github.rest.issues.getLabel({ owner, repo, name: labelName });
            } catch (e) {
              if (e.status === 404) {
                await github.rest.issues.createLabel({
                  owner, repo, name: labelName, color: "0E8A16", description: "Auto-created welcome label"
                });
              } else {
                throw e;
              }
            }

            // Skip if already present
            const { data: issues } = await github.rest.issues.listForRepo({
              owner, repo, state: "open", labels: labelName, per_page: 100
            });
            if (issues.some(i => i.title === title)) {
              console.log("Welcome issue already exists.");
              return;
            }

            await github.rest.issues.create({
              owner, repo,
              title,
              labels: [labelName],
              body: [
                "## Welcome to your portfolio repository!",
                "",
                "Complete your [setup checklist](setup/ONBOARDING-CHECKLIST.md) to get started.",
                "",
                "### Next Steps:",
                "1. Follow the setup checklist",
                "2. Update your README with your profile links",
                "3. Submit to Canvas when complete",
                "",
                "Close this issue when you're done!"
              ].join("\n")
            });
            console.log("✅ Welcome issue created!");
