name: Setup Progress Tracker
on:
  push:
    paths:
      - 'setup/ONBOARDING-CHECKLIST.md'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  track_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check setup progress
        id: check-progress
        run: |
          if [ -f "setup/ONBOARDING-CHECKLIST.md" ]; then
            COMPLETED=$(grep -c '\[x\]' setup/ONBOARDING-CHECKLIST.md || echo "0")
            TOTAL=$(grep -c '\[ \]\|\[x\]' setup/ONBOARDING-CHECKLIST.md || echo "1")
          else
            COMPLETED=0
            TOTAL=1
          fi
          
          echo "completed=$COMPLETED" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "✅ Setup Progress: $COMPLETED/$TOTAL tasks completed"

      - name: Celebrate progress
        if: steps.check-progress.outputs.completed >= 1
        run: |
          echo "🎉 Great job! You've completed ${{ steps.check-progress.outputs.completed }} setup task(s)!"

      - name: Create Completion Issue
        if: steps.check-progress.outputs.completed >= 4
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Check if an issue with the 'completed' label already exists
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "all",
              labels: "completed"
            });
            
            // If no 'completed' issue is found, create a new one
            if (issues.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "🎉 Onboarding Complete!",
                body: "Congratulations, you've finished all the setup tasks! You're ready to start the project. Great work! ✨",
                labels: ["completed"]
              });
              core.info("Created the 'Onboarding Complete!' issue.");
            } else {
              core.info("Completion issue already exists. Skipping creation.");
            }
